name: MCNSAFlatcore
main: com.mcnsa.flatcore.MCNSAFlatcore
version: 1.0.1
author: matejdro
depend: [GriefPrevention]
commands:
    flatcore:
        description: Weekly challenges.
permissions:
    mcnsaflatcore.command.flatcore:
        default: op
    mcnsaflatcore.mod:
        default: op