name: Mantle
main: us.corenetwork.mantle.MantlePlugin
version: 1.2.0
author: matejdro
depend: [GriefPrevention, Core, ProtocolLib]
softdepend: [WorldGuard]
commands:
    mantle:
        description: Main command    
    nbt:
        description: Nanobot
    inspect:
        description: Structure inspector