name: Mantle
main: us.corenetwork.mantle.MantlePlugin
version: 1.4.0
author: matejdro
depend: [GriefPrevention, Core]
softdepend: [WorldGuard, ProtocolLib]
load: STARTUP
commands:
    mantle:
        description: Main command    
    nbt:
        description: Nanobot
    inspect:
        description: Structure inspector
    chase:
        description: Treasure Chase commands
    holo:
        description: 1.8 holograms
    title:
        description: 1.8 title command
    slimeballs:
        description: Slimeballs
    perks:
        description: Perks