name: MCNSAFlatcore
main: com.mcnsa.flatcore.MCNSAFlatcore
version: 1.2.0
author: matejdro
depend: [GriefPrevention, MCNSANanobot]
softdepend: [WorldGuard]
commands:
    flatcore:
        description: Main command    
    
permissions:
    mcnsaflatcore.command.flatcore:
        default: op
    mcnsaflatcore.mod:
        default: op